dwell_hub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from main_app import views

urlpatterns = [
    path('', views.home, name="home"),
    path('user', views.all_users, name="all"),
    path('signin', views.signin, name="signin"),
    path('signout', views.signout, name="signout"),
    path('search', views.search_users, name="search"),
    path('user/<int:user_id>', views.user_details, name="details"),
    path('user/delete/<int:user_id>', views.user_delete, name="delete"),
    path('user/update/<int:user_id>', views.user_update, name="update"),
    path('user', views.user, name="user"),


    path('property', views.property, name="property"),
    path('review', views.review, name="review"),
    path('message', views.message, name="message"),
    path('appointment', views.appointment, name="appointment"),
    path('payment', views.payment, name="payment"),

    path('properties', views.properties, name="properties"),
    path('property_details', views.property_details, name="property_details"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
import os.path
import uuid

from django.db import models


def unique_img_name(instance, filename):
    name = uuid.uuid4()
    print(name)
    ext = filename.split(".")[-1]
    full_name = f"{name}.{ext}"  # dtmf.png
    return os.path.join('users', 'property', full_name)


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=100)
    user_type = models.CharField(max_length=50)
    profile_picture = models.ImageField(upload_to="media/users", blank=True, null=True)
    phone = models.CharField(max_length=100)
    reg_date = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username


class Property(models.Model):
    landlord = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    address = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    bedrooms = models.IntegerField()
    bathrooms = models.IntegerField()
    availability = models.BooleanField(default=True)
    property_pic = models.ImageField(upload_to="media\property", blank=True, null=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    rating = models.IntegerField()
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    message_content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    status = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=50)  # e.g., 'M-Pesa'
    status = models.CharField(max_length=20)  # e.g., 'pending', 'completed', 'refunded'

    def __str__(self):
        return self.user.username

templates/about.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block content %}

{% endblock %}

templates/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert  {{ message.tags }} alert-dismissible">
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        {{ message }}
         </div>
    {% endfor %}

{% endif %}

templates/all_users.html
{% extends 'base_template.html' %}

{% block title %}
    All Users List
{% endblock %}
{% include 'navbar.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-7">

            {% include 'alerts.html' %}

                <table class="table">
                    <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>User Type</th>
                        <th>Phone No</th>
                        <th>Reg Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in user %}
                        <tr>
                            <td>
                                <a href="/user/{{ user.id }}">{{ user.username }}</a>
                            </td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.user_type }}</td>
                            <td>{{ user.phone }}</td>
                            <td>{{ user.reg_date }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>


                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if user.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href='?page={{ user.previous_page_number }}'>Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href='' tabindex="-1" aria-disabled="True">Previous</a>
                            </li>
                        {% endif %}
{#                        {% for i in user.paginator.page_range %}#}
{#                            {% if user.number == i %}#}
{#                                <li class="page-item active" aria-current="page">#}
{##}
{#                                </li>#}
{#                            {% else %}#}
{#                                <li class="page-item"><a class="page-link" href=''></a></li>#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
                        {% if user.has_next %}
                            <li class="page-item">
                                <a class="page-link" href='?page={{ user.next_page_number }}'>Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href='' tabindex="-1" aria-disabled="True">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}

templates/base_template.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>
{% block content %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/contact.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block content %}

  <div class="page-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <span class="breadcrumb"><a href="#">Home</a>  /  Contact Us</span>
          <h3>Contact Us</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="contact-page section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="section-heading">
            <h6>| Contact Us</h6>
            <h2>Get In Touch With Our Agents</h2>
          </div>
          <p>When you really need to download free CSS templates, please remember our website TemplateMo. Also, tell your friends about our website. Thank you for visiting. There is a variety of Bootstrap HTML CSS templates on our website. If you need more information, please contact us.</p>
          <div class="row">
            <div class="col-lg-12">
              <div class="item phone">
                <img src="{% static 'app/assets/images/phone-icon.png' %}" alt="" style="max-width: 52px;">
                <h6>010-020-0340<br><span>Phone Number</span></h6>
              </div>
            </div>
            <div class="col-lg-12">
              <div class="item email">
                <img src="{% static 'app/assets/images/email-icon.png' %}" alt="" style="max-width: 52px;">
                <h6>info@villa.co<br><span>Business Email</span></h6>
              </div>
            </div>
          </div>
        </div>
          <div class="main-button mt-3">
              <a href="{% url 'message' %}">Send Us Message</a>
            </div>
{#        <div class="col-lg-6">#}
{#          <form id="contact-form" action="" method="post">#}
{#            <div class="row">#}
{#              <div class="col-lg-12">#}
{#                <fieldset>#}
{#                  <label for="name">Full Name</label>#}
{#                  <input type="name" name="name" id="name" placeholder="Your Name..." autocomplete="on" required>#}
{#                </fieldset>#}
{#              </div>#}
{#              <div class="col-lg-12">#}
{#                <fieldset>#}
{#                  <label for="email">Email Address</label>#}
{#                  <input type="text" name="email" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your E-mail..." required="">#}
{#                </fieldset>#}
{#              </div>#}
{#              <div class="col-lg-12">#}
{#                <fieldset>#}
{#                  <label for="subject">Subject</label>#}
{#                  <input type="subject" name="subject" id="subject" placeholder="Subject..." autocomplete="on" >#}
{#                </fieldset>#}
{#              </div>#}
{#              <div class="col-lg-12">#}
{#                <fieldset>#}
{#                  <label for="message">Message</label>#}
{#                  <textarea name="message" id="message" placeholder="Your Message"></textarea>#}
{#                </fieldset>#}
{#              </div>#}
{#              <div class="col-lg-12">#}
{#                <fieldset>#}
{#                  <button type="submit" id="form-submit" class="orange-button">Send Message</button>#}
{#                </fieldset>#}
{#              </div>#}
{#            </div>#}
{#          </form>#}
{#        </div>#}
        <div class="col-lg-12">
          <div id="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth" width="100%" height="500px" frameborder="0" style="border:0; border-radius: 10px; box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.15);" allowfullscreen=""></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/login.html
 {% extends 'layouts/master.html' %}
{% load crispy_forms_filters %}
{% block title %}
	Sign In
{% endblock %}

{% block content %}

	<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-4">
            <form action="{% url 'signin' %}" method="post" enctype="multipart/form-data" class="shadow py-4 px-3 mt-3">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-dark rounded-0 w-100">Sign In</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/navbar.html
<nav class="navbar sticky-top navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'user' %}">Dwell Hub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                <li class="nav-item">
                    <a class="nav-link {% if "/" == request.path %} active {% endif %}" aria-current="page"
                       href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if "/user"  == request.path %} active {% endif %}" href="{% url 'all' %}">Users</a>
                </li>

            </ul>
            <form class="d-flex" role="search" method="get" action="{% url 'search' %}">
                <input class="form-control me-2" name="search_word" type="search" placeholder="Search"
                       aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

            <ul class="navbar-nav me-3 mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-danger" href="#" role="button" data-bs-toggle="dropdown">{{ user.username }}</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'signout' %}">Sign Out</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/properties.html
{% extends 'layouts/master.html' %}
{% load static %}

{% block content %}

  <div class="page-heading header-text">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <span class="breadcrumb"><a href="#">Home</a> / Properties</span>
          <h3>Properties</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="section properties">
    <div class="container">
      <ul class="properties-filter">
        <li>
          <a class="is_active" href="#!" data-filter="*">Show All</a>
        </li>
        <li>
          <a href="#!" data-filter=".adv">Apartment</a>
        </li>
        <li>
          <a href="#!" data-filter=".str">Villa House</a>
        </li>
        <li>
          <a href="#!" data-filter=".rac">Penthouse</a>
        </li>
      </ul>
      <div class="row properties-box">
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 adv">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-01.jpg' %}" alt="" style="max-width: 60px; padding: 0px;"></a>

            <span class="category">Luxury Villa</span>
            <h6>$2.264.000</h6>
            <h4><a href="{% url 'property_details' %}">18 Old Street Miami, OR 97219</a></h4>
            <ul>
              <li>Bedrooms: <span>8</span></li>
              <li>Bathrooms: <span>8</span></li>
              <li>Area: <span>545m2</span></li>
              <li>Floor: <span>3</span></li>
              <li>Parking: <span>6 spots</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 str">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-02.jpg' %}" alt=""></a>
            <span class="category">Luxury Villa</span>
            <h6>$1.180.000</h6>
            <h4><a href="{% url 'property_details' %}">54 New Street Florida, OR 27001</a></h4>
            <ul>
              <li>Bedrooms: <span>6</span></li>
              <li>Bathrooms: <span>5</span></li>
              <li>Area: <span>450m2</span></li>
              <li>Floor: <span>3</span></li>
              <li>Parking: <span>8 spots</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 adv rac">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-03.jpg' %}" alt=""></a>
            <span class="category">Luxury Villa</span>
            <h6>$1.460.000</h6>
            <h4><a href="{% url 'property_details' %}">26 Mid Street Portland, OR 38540</a></h4>
            <ul>
              <li>Bedrooms: <span>5</span></li>
              <li>Bathrooms: <span>4</span></li>
              <li>Area: <span>225m2</span></li>
              <li>Floor: <span>3</span></li>
              <li>Parking: <span>10 spots</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 str">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-04.jpg' %}" alt=""></a>
            <span class="category">Apartment</span>
            <h6>$584.500</h6>
            <h4><a href="{% url 'property_details' %}">12 Hope Street Portland, OR 12650</a></h4>
            <ul>
              <li>Bedrooms: <span>4</span></li>
              <li>Bathrooms: <span>3</span></li>
              <li>Area: <span>125m2</span></li>
              <li>Floor: <span>25th</span></li>
              <li>Parking: <span>2 cars</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 rac str">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-05.jpg' %}" alt=""></a>
            <span class="category">Penthouse</span>
            <h6>$925.600</h6>
            <h4><a href="{% url 'property_details' %}">34 Hope Street Portland, OR 42680</a></h4>
            <ul>
              <li>Bedrooms: <span>4</span></li>
              <li>Bathrooms: <span>4</span></li>
              <li>Area: <span>180m2</span></li>
              <li>Floor: <span>38th</span></li>
              <li>Parking: <span>2 cars</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 rac adv">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-06.jpg' %}" alt=""></a>
            <span class="category">Modern Condo</span>
            <h6>$450.000</h6>
            <h4><a href="{% url 'property_details' %}">22 Hope Street Portland, OR 16540</a></h4>
            <ul>
              <li>Bedrooms: <span>3</span></li>
              <li>Bathrooms: <span>2</span></li>
              <li>Area: <span>165m2</span></li>
              <li>Floor: <span>26th</span></li>
              <li>Parking: <span>3 cars</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 rac str">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-03.jpg' %}" alt=""></a>
            <span class="category">Luxury Villa</span>
            <h6>$980.000</h6>
            <h4><a href=" {% url 'property_details' %}">14 Mid Street Miami, OR 36450</a></h4>
            <ul>
              <li>Bedrooms: <span>8</span></li>
              <li>Bathrooms: <span>8</span></li>
              <li>Area: <span>550m2</span></li>
              <li>Floor: <span>3</span></li>
              <li>Parking: <span>12 spots</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 rac adv">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-02.jpg' %}" alt=""></a>
            <span class="category">Luxury Villa</span>
            <h6>$1.520.000</h6>
            <h4><a href="{% url 'property_details' %}">26 Old Street Miami, OR 12870</a></h4>
            <ul>
              <li>Bedrooms: <span>12</span></li>
              <li>Bathrooms: <span>15</span></li>
              <li>Area: <span>380m2</span></li>
              <li>Floor: <span>3</span></li>
              <li>Parking: <span>14 spots</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 rac adv">
          <div class="item">
            <a href="{% url 'property_details' %}"><img src="{% static 'app/assets/images/property-01.jpg' %}" alt=""></a>
            <span class="category">Luxury Villa</span>
            <h6>$3.145.000</h6>
            <h4><a href="{% url 'property_details' %}">34 New Street Miami, OR 24650</a></h4>
            <ul>
              <li>Bedrooms: <span>10</span></li>
              <li>Bathrooms: <span>12</span></li>
              <li>Area: <span>860m2</span></li>
              <li>Floor: <span>3</span></li>
              <li>Parking: <span>10 spots</span></li>
            </ul>
            <div class="main-button">
              <a href="{% url 'appointment' %}">Schedule a visit</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <ul class="pagination">
            <li><a href="#">1</a></li>
            <li><a class="is_active" href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">>></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/update.html
{% extends 'base_template.html' %}
{% load crispy_forms_filters %}
{% block title %}
	Update User
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
	<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-4">
            <form action="{{ request.path }}" method="post" enctype="multipart/form-data" class="shadow py-4 px-3 mt-3">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-dark rounded-0 w-100">Update User</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/user_details.html
{% extends 'base_template.html' %}
{% load humanize %}

{% block title %}
	{{ user.username }}
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-5">

        {% include 'alerts.html' %}


            <div class="card">
                {% if user.profile_picture %}
                    <img src="{{ user.profile_picture.url }}" height="300" width="300" alt="" >
                {% endif %}

                <div class="card-body">
                    <h2 class="card-title">{{ user.username | title }}</h2>
                    <p class="card-text">Address: {{ user.email }}</p>
                    <p class="card-text">User Type: {{ user.user_type }}</p>
                    <p class="card-text">Phone: {{ user.phone }}</p>
                    <p class="card-text">Registered on: {{ user.reg_date }}</p>
                    <p class="card-text">Added On: {{ user.created_at | naturaltime }}</p>
                    <p class="card-text">Updated at: {{ user.updated_at | naturaltime }}</p>
                    {% if perms.main_app.delete_user %}
                    	<a href="{% url 'delete' user.id %}" class="btn btn-danger w-100">Delete</a>
                    {% endif %}

                    

                    {% if perms.main_app.change_user %}
                        <a href="{% url 'update' user.id %}" class="btn btn-info w-100 mt-3">Update</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}